name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # gradlew ကို Permission ပေးတာပါ
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # settings.gradle နဲ့ build.gradle မငြိအောင် အတင်းအကျပ် Build လုပ်ခိုင်းတဲ့အဆင့်
      - name: Build with Gradle
        run: ./gradlew assembleRelease --no-daemon

      # ထွက်လာမယ့် APK ဖိုင်ကို Upload တင်ပေးမယ့်အဆင့်
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: "**/build/outputs/apk/release/*-release.apk"
