name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # အလုပ်အားလုံးကို food folder ထဲမှာပဲ တိုက်ရိုက်လုပ်ဖို့ သတ်မှတ်ပေးလိုက်တာပါ
    defaults:
      run:
        working-directory: food

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: food/build/app/outputs/flutter-apk/app-release.apk
